apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SkylarHoughtonGithub/shoutsky-argo.git
    targetRevision: HEAD
    path: apps/backstage/overlays/dev
    plugin:
      name: argocd-helm-kustomize  # Special plugin that handles both
    helm:
      valueFiles:
        - ../../base/values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
