# apps/backstage/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: backstage-versions
    literals:
      - APP_VERSION=1.21.0
      - CHART_VERSION=1.0.0

resources:
  - servicemonitor.yaml