backstage:
  image:
    registry: ghcr.io
    repository: backstage/backstage
    pullPolicy: IfNotPresent

  database:
    client: pg

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

  postgresql:
    enabled: true
    persistence:
      enabled: true