backstage:
  image:
    tag: "latest"  # Use latest for dev

  ingress:
    host: backstage.dev.example.com

  resources:
    limits:
      memory: "1Gi"
      cpu: "500m"
    requests:
      memory: "512Mi"
      cpu: "250m"

  postgresql:
    persistence:
      size: "10Gi"