# apiVersion: v1
# kind: Secret
# metadata:
#   name: prod_usw-secret
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: cluster
#     environment: dev
# type: Opaque
# stringData:
#   name: prod_usw
#   server: https://kubernetes.dev.example.com
#   config: |
#     {
#       "bearerToken": "<token>",
#       "tlsClientConfig": {
#         "insecure": false,
#         "caData": "<base64-ca-data>"
#       }
#     }
