apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backstage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
  endpoints:
    - port: http
      path: /metrics