---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
- name: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 8.0.9
  releaseName: argocd
  namespace: argocd
  valuesFile: helm-chart/values.yaml

commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/component: argocd
  environment: dev