createAggregateRoles: true
namespaceOverride: argocd
global:
  domain: argocd.local

configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
params:
  server.insecure: true
  server.disable.auth: false

server:
  config:
    configManagementPlugins: |
      - name: sops
        generate:
          command: ["sh", "-c"]
          args: ["sops -d $ARGOCD_APP_SOURCE_PATH/secrets.enc.yaml"]
