apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage-dev
type: Opaque
stringData:
  # Backstage Auth
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
  
  # Backstage Database Connection
  POSTGRES_HOST: "backstage-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
---
# Separate secret for PostgreSQL (Helm chart expects this format)
apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgresql
  namespace: backstage-dev
type: Opaque
stringData:
  postgres-password: "${POSTGRES_PASSWORD}"  # superuser password
  password: "${POSTGRES_APP_PASSWORD}"       # application user password
  replication-password: "${POSTGRES_REPL_PASSWORD}"  # replication user password