apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage-dev
resources:
  - ../../base

helmCharts:
  - name: backstage
    repo: https://backstage.github.io/charts
    version: 1.0.0
    releaseName: backstage